export BUN_INSTALL="$HOME/.bun"
export VOLTA_HOME="$HOME/.volta"
export BREW_PATH="/opt/homebrew"
export PATH="$BREW_PATH/bin:$BUN_INSTALL/bin:$VOLTA_HOME/bin:$HOME/.local/bin:$PATH"


# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi

eval "$(/opt/homebrew/bin/brew shellenv)"
