if command -v brew >/dev/null 2>&1; then
    eval "$(brew shellenv)"
fi

export XDG_CONFIG_HOME="$HOME/.config"

export VOLTA_HOME="$HOME/.volta"
export BREW_PATH="/opt/homebrew"
export CARGO_PATH="$HOME/.cargo/bin"
export RACKET_PATH="/Applications/Racket v9.1/bin"
export PATH="$BREW_PATH/bin:$VOLTA_HOME/bin:$CARGO_PATH:$RACKET_PATH:$HOME/.local/bin:$PATH"

 # Prefer GNU userland over BSD
  for gnu_tool in coreutils gnu-sed findutils gawk make grep; do
      gnubin="$BREW_PATH/opt/$gnu_tool/libexec/gnubin"
      if [ -d "$gnubin" ]; then
          PATH="$gnubin:$PATH"
      fi
  done

export INFOPATH="$HOME/.local/share/info:$INFOPATH"


# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi


# Added by Obsidian
export PATH="$PATH:/Applications/Obsidian.app/Contents/MacOS"
