local wezterm = require("wezterm")
local config = wezterm.config_builder()

local sessionizer = wezterm.plugin.require("https://github.com/mikkasendke/sessionizer.wezterm")
local sessionizer_schema = {
	sessionizer.FdSearch({ wezterm.home_dir .. "/s", fd_path = "/opt/homebrew/bin/fd" }),
	{ label = "general", id = wezterm.home_dir },
	{ label = "~/notes", id = wezterm.home_dir .. "/notes" },
	{ label = "~/s/l/learn-node", id = wezterm.home_dir .. "/s/l/learn-node" },
	processing = sessionizer.for_each_entry(function(entry)
		entry.label = entry.label:gsub(wezterm.home_dir, "~")
	end),
	options = {
		title = "",
		prompt = "> ",
		always_fuzzy = true,
	},
}

local stack = wezterm.plugin.require("https://github.com/bad-noodles/stack.wez")
stack.apply_to_config(config)

local chord = wezterm.plugin.require("https://github.com/sravioli/chord.wz")
chord.setup({
	command = { key = "<leader>c" },
})

local resurrect = wezterm.plugin.require("https://github.com/StephenGemin/resurrect.wezterm")
resurrect.setup(config, {
	periodic_interval = 300,
	save_on_focus_loss = true,
	keybindings = false,
	status_bar = false,
})
wezterm.on("gui-startup", resurrect.state_manager.resurrect_on_gui_startup)

-- ember palette — generated by scripts/gen-palette from nvim's base16
local palette = dofile(wezterm.config_dir .. "/palette.lua")
config.colors = palette

config.font = wezterm.font("JetBrainsMono Nerd Font")
config.font_size = 16

config.window_close_confirmation = "NeverPrompt"

config.tab_bar_at_bottom = true
config.show_new_tab_button_in_tab_bar = false
config.window_decorations = "RESIZE"

local bar = wezterm.plugin.require("https://github.com/adriankarlen/bar.wezterm")
bar.apply_to_config(config, {
	separator = {
		space = 1,
		left_icon = "",
		right_icon = "",
	},
	padding = {
		tabs = { left = 1, right = 1 },
	},
	modules = {
		spotify = { enabled = false },
		ssh = { enabled = false },
		clock = { enabled = false },
		username = { enabled = false },
		hostname = { enabled = false },
		cwd = { enabled = true },
	},
})

config.colors.tab_bar = {
	background = palette.background,
	active_tab = { bg_color = palette.background, fg_color = "#e0b341" },
	inactive_tab = { bg_color = palette.background, fg_color = palette.foreground },
	new_tab = { bg_color = palette.background, fg_color = palette.foreground },
}

config.leader = { key = "Space", mods = "CTRL", timeout_milliseconds = 1000 }

chord.maps(config, {
	{ "<leader><Space>", sessionizer.show(sessionizer_schema), "sessionizer" },
	{ "<leader>w", wezterm.action.SplitPane({ direction = "Right" }), "split horizontal" },
	{ "<leader>v", wezterm.action.SplitPane({ direction = "Down" }), "split vertical" },
})

local resurrect_mode = chord.mode("resurrect_mode", {
	meta = { i = "R", txt = "RESURRECT" },
	keys = {
		{ "s", resurrect.workspace_state.save_workspace_action(), "save workspace" },
		{
			"r",
			resurrect.fuzzy_loader.restore_action({
				relative = true,
				restore_text = true,
				on_pane_restore = resurrect.pane_tree.default_on_pane_restore,
			}),
			"restore",
		},
		{ "d", resurrect.fuzzy_loader.delete_action(), "delete" },
		{ "<ESC>", "PopKeyTable", "exit" },
	},
})
chord.tables(config, { resurrect_mode })
config.keys[#config.keys + 1] = resurrect_mode:activate("<leader>s", "resurrect")

local function is_vim(pane)
	return pane:get_user_vars().IS_NVIM == "true"
end

local direction_keys = {
	h = "Left",
	j = "Down",
	k = "Up",
	l = "Right",
}

local function split_nav(key)
	return {
		key = key,
		mods = "CTRL",
		action = wezterm.action_callback(function(win, pane)
			if is_vim(pane) then
				win:perform_action({ SendKey = { key = key, mods = "CTRL" } }, pane)
			else
				win:perform_action({ ActivatePaneDirection = direction_keys[key] }, pane)
			end
		end),
	}
end

for key, _ in pairs(direction_keys) do
	config.keys[#config.keys + 1] = split_nav(key)
	config.keys[#config.keys + 1] = {
		key = key,
		mods = "CTRL|SHIFT",
		action = wezterm.action.AdjustPaneSize({ direction_keys[key], 3 }),
	}
end

config.keys[#config.keys + 1] = { key = "s", mods = "CMD|SHIFT", action = stack.action.SpawnPane }
config.keys[#config.keys + 1] = { key = "k", mods = "CMD|SHIFT", action = stack.action.ActivatePaneRelative(-1) }
config.keys[#config.keys + 1] = { key = "j", mods = "CMD|SHIFT", action = stack.action.ActivatePaneRelative(1) }

config.keys[#config.keys + 1] = {
	key = "l",
	mods = "CMD",
	action = wezterm.action_callback(function(win, pane)
		win:perform_action({ SendKey = { key = "l", mods = "CTRL" } }, pane)
	end),
}

return config
