palette = "everforest"
# Remove default newline between prompts
add_newline = false

# General prompt settings
format = "$directory$git_branch$git_status$git_state$character"
right_format = "$bun$nodejs"

# Disable line break to keep everything on one line
[line_break]
disabled = true

# Directory configuration
[directory]
format = "[$path ]($style)"
style = "purple"
truncation_length = 3
truncate_to_repo = false
home_symbol = "~"

# Git branch
[git_branch]
format = "[$branch(:$remote_branch) ]($style)"
style = "aqua"
symbol = ""

# Git status
[git_status]
format = "([\\[$all_status$ahead_behind\\] ]($style))"
style = "aqua"
ahead = "↑${count}"
behind = "↓${count}"
up_to_date = ""
diverged = "↑${ahead_count}↓${behind_count}"
conflicted = "󰞇${count}"
deleted = "✘${count}"
renamed = "󰁕${count}"
modified = "󰷈${count}"
staged = "✚${count}"
untracked = "?${count}"
stashed = "󰏗"

# Git state (merge, rebase, etc.)
[git_state]
format = "([\\($state( $progress_current of $progress_total)\\) ]($style))"
style = "aqua"
cherry_pick = " CHERRY-PICK"
rebase = "󰑖 REBASE"
merge = " MERGE"
revert = "󰕍 REVERT"
bisect = " BISECT"

# Node.js - only show in Node projects
[nodejs]
format = "[$symbol$version]($style)"
style = "green"
version_format = "v${major}"
symbol = "󰎙 "
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]
detect_files = ["package.json", ".nvmrc", ".node-version"]
detect_folders = ["node_modules"]
not_capable_style = "disabled"

# Bun - only show in Bun projects
[bun]
format = "[$symbol]($style)"
symbol = " "
style = "fg"

# Prompt character with error indication
[character]
success_symbol = "[󰄛](aqua)"
error_symbol = "[󰄛](red)"
vicmd_symbol = "[󰄛](aqua)"

[palettes.everforest]
# Background colors
bg_dim = "#1e2326"
bg0 = "#272e33"
bg1 = "#2e383c"
bg2 = "#374145"
bg3 = "#414b50"
bg4 = "#495156"
bg5 = "#4f5b58"

# Foreground colors
fg = "#d3c6aa"
red = "#e67e80"
orange = "#e69875"
yellow = "#dbbc7f"
green = "#a7c080"
blue = "#7fbbb3"
aqua = "#83c092"
purple = "#d699b6"

# Grayed out colors
grey0 = "#7a8478"
grey1 = "#859289"
grey2 = "#9da9a0"

# Status line colors
statusline1 = "#a7c080"
statusline2 = "#d3c6aa"
statusline3 = "#e67e80"
