#!/usr/bin/env bash

gold=$(tput setaf 3); red=$(tput setaf 1); dim=$(tput dim); reset=$(tput sgr0)

script_name=$1

if [[ -z "$script_name" ]];then
    printf "%s✗%s provide a script name.\n" "$red" "$reset" >&2
    exit 1
fi

if [[ -s $script_name ]]; then
    printf "%s↻%s %s already exists.\n" "$gold" "$reset" "$script_name"
    printf "%s" "$dim"
    head -n 5 "$script_name"
    printf "%s" "$reset"
    read -p "open file? (y/n) " open
    case "$open" in
        y)
            nvim "$script_name"
            exit
            ;;
        n) exit ;;
    esac
fi

echo '#!/usr/bin/env bash' > "$script_name" && chmod +x "$script_name" && nvim "$script_name"
