#!/usr/bin/env bash

script_name=$1

if [[ -z "$script_name" ]];then
    echo 'provide a script name.' >&2
    exit 1
fi

if [[ -s $script_name ]]; then
    echo "$script_name already exists."
    head -n 5 "$script_name"
    read -p "open file? (y/n) " open
    case "$open" in
        y)
            nvim "$script_name"
            exit
            ;;
        n) exit ;;
    esac
fi

echo '#!/usr/bin/env bash' > "$script_name" && chmod +x "$script_name" && nvim "$script_name"
