#!/bin/zsh

gold=$(tput setaf 3); green=$(tput setaf 2); red=$(tput setaf 1); dim=$(tput dim); reset=$(tput sgr0)

all_flag=false
preview_flag=false

usage() {
  printf "%sUsage:%s %s [-a] [-p]\n" "$gold" "$reset" "$0"
  echo "  -a           Delete all screenshots without confirmation for each one"
  echo "  -p           Show preview of files before delete (doesn't work with -a)"
  exit 1
}

process_file() {
  local current=$1
  local total=$2
  local filename=$3


  printf "%sFile %s of %s:%s %s\n" "$dim" "$current" "$total" "$reset" "${file:t}"
  if $preview_flag; then
    viu $file
  fi
  printf "Delete the file? %s(y/n/q):%s " "$dim" "$reset"
  read command

  case $command in
    "y")
      rm "$file"
      printf "%s✓%s file removed\n" "$green" "$reset"
      ((current++))
      continue 2
      ;;
    "n")
      printf "%s↻%s keeping file\n" "$gold" "$reset"
      ((current++))
      continue 2
      ;;
    "q")
      exit 0
      ;;
    *)
      printf "%s✗%s invalid command. type y to delete, n to keep, q to quit:\n" "$red" "$reset"
      ;;
    esac

}

while getopts ":pa" opt; do
  case $opt in
    a) 
      all_flag=true
      ;;
    p)
      preview_flag=true
      ;;
    \?)
      printf "%s✗%s invalid option: -%s\n" "$red" "$reset" "$OPTARG"
      usage
      ;;
  esac
done

shift $((OPTIND-1))

setopt nullglob  # Enable nullglob just for this section

files=(~/Desktop/{Screenshot,screenshot}*.png)

# Check if any files were found
if [ ${#files} -eq 0 ]; then
    printf "%s✗%s no matching files found\n" "$red" "$reset"
    exit 0
fi

unsetopt nullglob  # Restore default behavior

total=${#files}




current=1

for file in $files; do

if ! $all_flag; then
    while true; do
      process_file $current $total $file
    done
else
  printf "%s✓%s removing file: %s\n" "$green" "$reset" "${file:t}"
  rm $file
fi
done

printf "%s✓%s processing complete\n" "$green" "$reset"
