gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - '#a7c080'
      - bold
    inactiveBorderColor:
      - '#414b50'
    searchingActiveBorderColor:
      - '#dbbc7f'
      - bold
    optionsTextColor:
      - '#7fbbb3'
    selectedLineBgColor:
      - '#374145'
    selectedRangeBgColor:
      - '#374145'
    cherryPickedCommitBgColor:
      - '#d699b6'
    cherryPickedCommitFgColor:
      - '#272e33'
    unstagedChangesColor:
      - '#e67e80'
    defaultFgColor:
      - '#d3c6aa'
