gui:
  theme:
    activeBorderColor:
      - '#e0b341'
      - bold
    inactiveBorderColor:
      - '#6f655a'
    searchingActiveBorderColor:
      - '#cf9163'
      - bold
    optionsTextColor:
      - '#948a7d'
    selectedLineBgColor:
      - '#2a2521'
    cherryPickedCommitBgColor:
      - '#e0b341'
    cherryPickedCommitFgColor:
      - '#000000'
    unstagedChangesColor:
      - '#c77b6b'
    defaultFgColor:
      - '#c8bfae'
