gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  timeFormat: 02 Jan 2006
  shortTimeFormat: 13:04
  theme:
    activeBorderColor:
      - '#eecc6c'
      - bold
    inactiveBorderColor:
      - '#333333'
    searchingActiveBorderColor:
      - '#aaaaaa'
      - bold
    optionsTextColor:
      - '#999999'
    selectedLineBgColor:
      - '#222222'
    cherryPickedCommitBgColor:
      - '#eecc6c'
    cherryPickedCommitFgColor:
      - '#000000'
    unstagedChangesColor:
      - '#5f8787'
    defaultFgColor:
      - '#c1c1c1'
  commitLength:
    show: true
  showListFooter: false
  fileTreeSortOrder: mixed
  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: true
  showDivergenceFromBaseBranch: arrowAndNumber
  filterMode: fuzzy
  statusPanelView: allBranchesLog
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=format:'%C(yellow)%h%Creset -%C(auto)%d%Creset %s %C(dim white)(%cr) %C(blue)<%an>%Creset' {{branchName}} --
  log:
    showWholeGraph: true
notARepository: quit
disableStartupPopups: true
