gui:
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  timeFormat: 02 Jan 2006
  shortTimeFormat: 13:04

  theme:
    activeBorderColor:
      - '#e0b341'
      - bold
    inactiveBorderColor:
      - '#6f655a'
    searchingActiveBorderColor:
      - '#cf9163'
      - bold
    optionsTextColor:
      - '#948a7d'
    selectedLineBgColor:
      - '#2a2521'
    cherryPickedCommitBgColor:
      - '#e0b341'
    cherryPickedCommitFgColor:
      - '#000000'
    unstagedChangesColor:
      - '#c77b6b'
    defaultFgColor:
      - '#c8bfae'

  commitLength:
    show: true

  showListFooter: false
  fileTreeSortOrder: mixed

  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: true
  showDivergenceFromBaseBranch: arrowAndNumber

  filterMode: fuzzy
  statusPanelView: allBranchesLog

git:
  pagers:
    - pager: diff-so-fancy

  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=format:'%C(yellow)%h%Creset -%C(auto)%d%Creset %s %C(dim white)(%cr) %C(blue)<%an>%Creset' {{branchName}} --

  log:
    showWholeGraph: true

notARepository: quit
disableStartupPopups: true
